/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    ReminderForm: typeof import('./src/components/ReminderForm.vue')['default']
    ReminderModal: typeof import('./src/components/ReminderModal.vue')['default']
  }
}
